<template>
	<div>
		<h2>分类</h2>
		<scroll>
			<li>as1</li>
			<li>as2</li>
			<li>as3</li>
			<li>as4</li>
			<li>as5</li>
			<li>as6</li>
			<li>as7</li>
			<li>as8</li>
			<li>as9</li>
			<li>as10</li>
			<li>as11</li>
			<li>as12</li>
			<li>as13</li>
			<li>as14</li>
			<li>as15</li>
			<li>as16</li>
			<li>as17</li>
			<li>as18</li>
			<li>as19</li>
			<li>as20</li>
			<li>as21</li>
			<li>as22</li>
			<li>as23</li>
			<li>as24</li>
			<li>as25</li>
			<li>as26</li>
			<li>as27</li>
			<li>as28</li>
			<li>as29</li>
			<li>as30</li>
			<li>as31</li>
			<li>as32</li>
			<li>as33</li>
			<li>as34</li>
			<li>as35</li>
			<li>as36</li>
			<li>as37</li>
			<li>as38</li>
			<li>as39</li>
			<li>as40</li>
			<li>as41</li>
			<li>as42</li>
			<li>as43</li>
			<li>as44</li>
			<li>as45</li>
			<li>as46</li>
			<li>as47</li>
			<li>as48</li>
			<li>as49</li>
			<li>as50</li>
			<li>as51</li>
			<li>as52</li>
			<li>as53</li>
			<li>as54</li>
			<li>as55</li>
			<li>as56</li>
			<li>as57</li>
			<li>as58</li>
			<li>as59</li>
			<li>as60</li>
			<li>as61</li>
			<li>as62</li>
			<li>as63</li>
			<li>as64</li>
			<li>as65</li>
			<li>as66</li>
			<li>as67</li>
			<li>as68</li>
			<li>as69</li>
			<li>as70</li>
			<li>as71</li>
			<li>as72</li>
			<li>as73</li>
			<li>as74</li>
			<li>as75</li>
			<li>as76</li>
			<li>as77</li>
			<li>as78</li>
			<li>as79</li>
			<li>as80</li>
			<li>as81</li>
			<li>as82</li>
			<li>as83</li>
			<li>as84</li>
			<li>as85</li>
			<li>as86</li>
			<li>as87</li>
			<li>as88</li>
			<li>as89</li>
			<li>as90</li>
			<li>as91</li>
			<li>as92</li>
			<li>as93</li>
			<li>as94</li>
			<li>as95</li>
			<li>as96</li>
			<li>as97</li>
			<li>as98</li>
			<li>as99</li>
			<li>as100</li>
		</scroll>
	</div>
</template>

<script>
	import Scroll from '@/components/common/scroll/Scroll.vue'

	export default{
		name:"Menu",
		components:{
			"scroll":Scroll
		},
		data(){
			return{
				bs:null
			}
		}
	}
</script>

<style>

</style>
